### ISSUE TITLE
Wenn man alle Hintsteine hat und noch einen bekommt alles dunkel

### ISSUE THREAD

**Issue by dnowak94** [Teizakk/Swegruppe10escapegame#107]
https://drive.google.com/file/d/0B8MAkFt5J2TSd25BVkduaDRBdmc/view?usp=sharing

**Comment by Kyurai** [comment]
Ist bei mir noch nie passiert !

**Comment by Kyurai** [comment]
aber du hast dir die ja auch gecheatet ! du hast 1 punkt und 5 hinweissteine
