### ISSUE TITLE
Truhe öffnen :IndexOutOfRangeException

### ISSUE THREAD

**Issue by juergenbernhardt** [Teizakk/Swegruppe10escapegame#120]
IndexOutOfRangeException: Array index is out of range.
Assets.Code.Models.Question.get_ImagePath () (at Assets/Code/Models/Question.cs:21)
Assets.Code.Scripts.SceneControllers.QuestionDialogController.LoadQuestion () (at Assets/Code/Scripts/SceneControllers/QuestionDialogController.cs:370)
Assets.Code.Scripts.SceneControllers.QuestionDialogController.ShowQuestion () (at Assets/Code/Scripts/SceneControllers/QuestionDialogController.cs:90)
Assets.Code.Manager.GameStateManager.OpenChest (UnityEngine.GameObject chestToOpen) (at Assets/Code/Manager/GameStateManager.cs:344)
Assets.Code.Scripts.FeatureScripts.PlayerScript.OnTriggerStay (UnityEngine.Collider other) (at Assets/Code/Scripts/FeatureScripts/PlayerScript.cs:138)

**Comment by Saltzmann** [comment]
das war hauptsächlich bei fehlerhaften datensätzen der Fall aber wunder mich trotzdem wieso das noch auftritt, gerade wenn du die aktuellste version hattest
