### ISSUE TITLE
Spiel startenschlägt fehl

### ISSUE THREAD

**Issue by schmetzyannick** [Teizakk/Swegruppe10escapegame#72]
Wenn man das Spiel startet kommen folgende Fehlermeldungen (hab gerade master gezogen und gebuildet). In der exe steht dann:
C:/Users/Yannick/AppData/LocalLow/SWEGruppe10/The Mighty Quest For Epic Grades\Modules\DNIS existiert nicht!
Konnte Moduldatei: DNIS nicht öffnen/laden!

**Comment by Saltzmann** [comment]
Dann solltest du auch das machen, was ich noch geschrieben habe und die zip in den genannten Ordner kopieren - da sind die Fragen etc drin ;)
