### ISSUE TITLE
Module.txt ist nicht vorhanden bei builden in anderen ordner

### ISSUE THREAD

**Issue by dnowak94** [Teizakk/Swegruppe10escapegame#76]
wozu war dieses Module.txt überhaupt?

**Comment by Saltzmann** [comment]
ist jetzt ein Artefakt alter Zeiten, was allerdings dazu dient die Module etwas umständlich zu kapseln. es sollte eigentlich funktionieren - aber wenn noch Zeit bleibt könnte man noch auf eine ähnliche Lösung wie bei den Savegames wechseln (ist allerdings ein bisschen gefährlich so kurz vor Abgabe)

**Comment by dnowak94** [comment]
ich hab das denke ich damit gelöst, dass ich das LoadFromFile durch Persist.GetModuleFiles() ersetzt hab

**Comment by Saltzmann** [comment]
kannst du dann gucken, ob es funktioniert die Module.txt komplett zu verbannen in dem du die Funktionalität rausnimmst, dass beim NewModule Dialog da rein gespeichert wird - das müsste ja dann auch überflüssig sein... 

Die Frage ist dann nur, ob das hinzufügen und die Fehlermeldungen aus diesem Dialog noch funktionieren, oder ob die auf der Datei aufgebaut haben. Wenn das reibungslos geht, dann weg mit der Module.txt wäre mir auch lieb 👍

**Comment by Redanski** [comment]
Fixed
