### ISSUE TITLE
Kisten leuchten

### ISSUE THREAD

**Issue by schmetzyannick** [Teizakk/Swegruppe10escapegame#81]
Manchmal kann aus leuchtenden Kisten nocheinmal eine Frage gezogen werden.
Kisten leuchten nicht immer wenn man eine Frage richtig beantwortet hat.
Kisten leuchten manchmal wenn man eine Frage falsch beantwortet hat.

**Comment by Saltzmann** [comment]
schreib doch gleich: "Kisten leuchten wenn sie Bock haben und nicht wenn sie sollen" 🤣

**Comment by schmetzyannick** [comment]
hahahaha :D jaja so ist es 👎
