### ISSUE TITLE
Kisten öffnen

### ISSUE THREAD

**Issue by schmetzyannick** [Teizakk/Swegruppe10escapegame#84]
Ab und zu (selten) folgende Fehlermeldung:

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[Assets.Code.Models.Question].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
Assets.Code.Manager.QuestionManager.ProvideUnusedQuestion (System.String chapter) (at Assets/Code/Manager/QuestionManager.cs:233)
Assets.Code.Scripts.SceneControllers.QuestionDialogController.LoadQuestion () (at Assets/Code/Scripts/SceneControllers/QuestionDialogController.cs:236)
Assets.Code.Scripts.SceneControllers.QuestionDialogController.ShowQuestion () (at Assets/Code/Scripts/SceneControllers/QuestionDialogController.cs:89)
Assets.Code.Manager.GameStateManager.OpenChest (UnityEngine.GameObject chestToOpen) (at Assets/Code/Manager/GameStateManager.cs:279)
Assets.Code.Scripts.FeatureScripts.PlayerScript.OnTriggerStay (UnityEngine.Collider other) (at Assets/Code/Scripts/FeatureScripts/PlayerScript.cs:135)

**Comment by Redanski** [comment]
Datei war Fehlerhaft
